DROP DATABASE IF EXISTS semana_5;

CREATE DATABASE semana_5 ;
USE semana_5;

CREATE TABLE usuarios (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
dni VARCHAR(11),
tlf INT UNSIGNED, 
email VARCHAR(150),
nombre VARCHAR(150),
apellidos VARCHAR(150),
pais VARCHAR(50),
cp SMALLINT UNSIGNED,
direccion1 VARCHAR(150),
direccion2 VARCHAR(150)
);

ALTER TABLE usuarios CHANGE dni dni VARCHAR(9);
ALTER TABLE usuarios CHANGE email email VARCHAR(100) NOT NULL, CHANGE nombre nombre VARCHAR(100) NOT NULL;